# 项目基础配置
app:
  name: PDF智能文件管理系统
  version: 1.0.0
  debug: true
  host: 0.0.0.0
  port: 5000
  secret_key: pdf_ai_doc_secret_key_2024

# 文件存储配置
file_storage:
  # 上传文件保存目录
  upload_dir: ./uploads
  # 处理后文件保存目录
  processed_dir: ./processed
  # 临时文件目录
  temp_dir: ./temp
  # 支持的文件类型
  allowed_extensions: [pdf]
  # 最大文件大小（MB）
  max_file_size: 100
  # 文件名编码
  filename_encoding: utf-8

# 日志配置
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: ./logs/app.log
  max_size: 50MB
  backup_count: 5
  console_output: true

# 内容处理配置
content_processing:
  # 并发处理数量
  max_workers: 4
  # 处理超时时间（秒）
  timeout: 300
  # 重试次数
  retry_times: 3
  
  # 图片处理配置
  image_processing:
    quality: 85
    max_width: 1920
    max_height: 1080
    format: JPEG
  
  # 文本提取配置
  text_extraction:
    min_text_length: 10
    remove_extra_spaces: true
    preserve_formatting: true

# API配置
api:
  # 请求限制
  rate_limit: 100/hour
  # 超时设置
  timeout: 30
  # 分页配置
  page_size: 20
  max_page_size: 100

# 安全配置
security:
  # CORS配置
  cors_enabled: true
  cors_origins: ["*"]
  # 文件安全扫描
  virus_scan_enabled: false
  # 上传文件验证
  file_validation: true

# 监控配置
monitoring:
  # 性能监控
  performance_monitoring: true
  # 错误追踪
  error_tracking: true
  # 指标收集
  metrics_collection: true 