# 提示词配置文件

# 系统角色提示词
system_prompts:
  # 智能检索系统角色
  search_assistant: |
    你是一个专业的PDF文档智能检索助手。你的任务是基于用户上传的PDF文档内容，为用户提供准确、有用的信息检索和分析服务。
    
    你具备以下能力：
    1. 理解和分析PDF文档中的文字、表格、图片、图表等各种内容
    2. 根据用户问题，从文档中检索相关信息
    3. 对检索到的信息进行智能整理和分析
    4. 提供准确、详细的回答，并注明信息来源
    
    请遵循以下原则：
    - 回答要准确，基于文档内容，不要编造信息
    - 回答要详细完整，包含必要的上下文
    - 对于表格和图表数据，要准确引用和解释
    - 如果文档中没有相关信息，请明确说明
    - 回答要结构化，便于用户理解

  # 内容分析系统角色  
  content_analyzer: |
    你是一个专业的PDF内容分析专家。你需要对PDF文档的内容进行深度分析和理解。
    
    你的任务包括：
    1. 识别文档的主题和结构
    2. 提取关键信息和实体
    3. 分析表格和图表的含义
    4. 建立内容之间的关联关系
    5. 生成内容摘要和标签
    
    分析时请注意：
    - 保持客观和准确
    - 识别不同类型的内容（文本、表格、图像等）
    - 提取实体关系，构建知识图谱
    - 为每个内容块生成合适的标签和摘要

# 任务特定提示词
task_prompts:
  # 文档摘要生成
  document_summary: |
    请为以下PDF文档内容生成一个详细的摘要：
    
    文档内容：{content}
    
    请包含以下要素：
    1. 文档主题和目的
    2. 关键信息点（3-5个）
    3. 主要数据和结论
    4. 文档结构概述
    
    摘要长度控制在200-300字。

  # 关键词提取
  keyword_extraction: |
    请从以下文档内容中提取10-15个最重要的关键词：
    
    内容：{content}
    
    要求：
    1. 关键词应该能代表文档的核心主题
    2. 包含专业术语和重要概念
    3. 按重要性排序
    4. 关键词之间用逗号分隔

  # 实体关系提取
  entity_relation_extraction: |
    请从以下内容中提取实体和它们之间的关系：
    
    内容：{content}
    
    请识别：
    1. 人物实体（人名、职位、组织等）
    2. 地点实体（地名、位置等）
    3. 时间实体（日期、时间等）
    4. 事件实体（活动、事件等）
    5. 概念实体（术语、概念等）
    
    并分析实体之间的关系，以JSON格式返回。

  # 表格分析
  table_analysis: |
    请分析以下表格内容：
    
    表格数据：{table_content}
    
    请提供：
    1. 表格的主题和用途
    2. 重要数据趋势和模式
    3. 关键数字和统计信息
    4. 数据的含义和解读
    5. 可能的结论和洞察

  # 图表分析
  chart_analysis: |
    请分析以下图表内容：
    
    图表描述：{chart_description}
    图表数据：{chart_data}
    
    请提供：
    1. 图表类型和展示的信息
    2. 数据趋势和变化
    3. 关键数据点
    4. 数据背后的含义
    5. 可能的结论

# 检索相关提示词
search_prompts:
  # 问答检索
  qa_search: |
    用户问题：{question}
    
    相关文档内容：
    {search_results}
    
    请基于以上文档内容回答用户问题。要求：
    1. 回答要准确，基于文档内容
    2. 如果文档中没有相关信息，请明确说明
    3. 引用具体的文档段落或数据
    4. 回答要详细完整
    5. 如果涉及多个文档，请注明来源

  # 语义检索优化
  semantic_search_optimization: |
    用户查询：{query}
    
    请将用户查询转换为更适合语义检索的查询词，要求：
    1. 扩展同义词和相关词汇
    2. 添加可能的专业术语
    3. 考虑不同的表达方式
    4. 保持查询的核心意图
    
    返回3-5个优化后的查询词。

  # 多轮对话上下文
  multi_turn_context: |
    对话历史：
    {conversation_history}
    
    当前用户问题：{current_question}
    
    相关文档内容：{search_results}
    
    请结合对话历史和文档内容回答当前问题，保持对话的连贯性。

# 错误处理提示词
error_prompts:
  # 无搜索结果
  no_search_results: |
    很抱歉，我在已上传的PDF文档中没有找到与您问题相关的信息。
    
    建议：
    1. 尝试使用不同的关键词重新提问
    2. 检查问题是否与文档主题相关
    3. 确认文档是否已正确上传和处理
    
    您可以：
    - 重新描述您的问题
    - 上传更多相关文档
    - 查看已上传文档的内容摘要

  # 处理错误
  processing_error: |
    文档处理过程中遇到错误。可能的原因：
    1. PDF文件格式不支持
    2. 文件内容无法正确解析
    3. 文件损坏或加密
    
    请检查文件并重新上传，或联系系统管理员。

# GraphRAG相关提示词
graph_rag_prompts:
  # 图谱构建
  graph_construction: |
    请基于以下内容构建知识图谱：
    
    内容：{content}
    
    需要识别：
    1. 核心实体及其属性
    2. 实体之间的关系
    3. 实体的重要性权重
    4. 关系的强度和类型
    
    以图数据库格式返回结果。

  # 图谱查询
  graph_query: |
    用户问题：{question}
    
    相关知识图谱路径：
    {graph_paths}
    
    相关文档内容：
    {document_content}
    
    请结合知识图谱的结构化信息和原始文档内容，提供全面的回答。

# 输出格式模板
output_templates:
  # 标准回答格式
  standard_answer: |
    **回答：**
    {answer}
    
    **信息来源：**
    {sources}
    
    **相关内容：**
    {related_content}

  # 分析报告格式
  analysis_report: |
    # 分析报告
    
    ## 主要发现
    {main_findings}
    
    ## 详细分析
    {detailed_analysis}
    
    ## 数据支撑
    {supporting_data}
    
    ## 结论建议
    {conclusions} 